version: '3'
services:
  pg-blip:
    image: pg-instruct-blip
    build:
      # context is upper directory (env_docker)
      context: ../
      dockerfile: ./env_docker/Dockerfile
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - ../pg-blip:/pg-blip
     - ../env_docker/requirements.txt:/requirements.txt
     - ../models:/models
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
     - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
     #- NVIDIA_VISIBLE_DEVICES=1 #A100 80GB 2nd
     - NVIDIA_VISIBLE_DEVICES=MIG-78fe31ba-2187-5cfe-ac8b-433427112f22 #A100 40GB MIG
     #- NVIDIA_VISIBLE_DEVICES=MIG-fe3895bf-a348-5909-b135-ee5531e1d393 #A100 40GB MIG

    working_dir: /pg-blip
    network_mode: host
    logging:
      driver: json-file

    command: python cuda.py
    #command: nvidia-smi -l
